CONNECT TO PRODUCAO;
GRANT CONNECT ON DATABASE TO USER DASHDBMON;
GRANT EXECUTE ON SPECIFIC FUNCTION SYSPROC.ENV_GET_SYSTEM_RESOURCES TO USER DASHDBMON;
GRANT EXECUTE ON SPECIFIC FUNCTION SYSPROC.MON_GET_PKG_CACHE_STMT TO USER DASHDBMON;
GRANT EXECUTE ON SPECIFIC FUNCTION SYSPROC.MON_GET_DATABASE TO USER DASHDBMON;
GRANT EXECUTE ON SPECIFIC FUNCTION SYSPROC.MON_GET_ACTIVITY TO USER DASHDBMON;
GRANT EXECUTE ON SPECIFIC FUNCTION SYSPROC.MON_GET_CONNECTION TO USER DASHDBMON;
CONNECT RESET;
